name: weather01

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 09 * * *'

jobs:
  docker:
    runs-on: windows-latest
    steps:
      - name: Set up QEMU
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: actions/setup-python@v3
         run: |
           python -m pip install --upgrade pip
           
         
